// packages/schema-table/src/mutli-column.vue
<script>
export default {
  name: 'MutliColumn',
  functional: true,
  props: {
    item: {
      type: Object,
      default() {
        return {}
      }
    }
  },
  render(h, ctx) {
    const { item } = ctx.props
    const CellContent = ctx.parent.cellContent
    const children = item.children && Array.isArray(item.children) && item.children.length > 0
      ? item.children.map((child) => h('mutli-column', {
        attrs: { item: child },
        scopedSlots: {
          default(props) {
            if (CellContent) {
              return CellContent.call(ctx, h, {
                row: props.row,
                $index: props.$index,
                label: props.column.label,
                prop: props.column.property
              })
            }
            return h('span', [props.row[props.column.property]])
          }
        }
      }))
      : null
    return h(
      'el-table-column',
      {
        attrs: {
          label: item.label,
          prop: item.prop,
          ...(item.attrs || {})
        },
        scopedSlots: {
          default(props) {
            if (CellContent) {
              return CellContent.call(ctx, h, {
                row: props.row,
                $index: props.$index,
                label: props.column.label,
                prop: props.column.property
              })
            }
            return h('span', [props.row[props.column.property]])
          }
        }
      },
      children
    )
  }
}
</script>

// packages/schema-table/src/MutliColumn.jsx
export default function MutliColumn(context) {
  const { itemColumn } = context.props

  const ElTableColumnDefaultSlot = (scope) => {
    return (
      <span>{ scope.row[scope.column.property] }</span>
    )
  }

  const children = Array.isArray(itemColumn.children) && itemColumn.children.map(t => {
    return (
      <MutliColumn
        item-column={t}
        scopedSlots={{
          default(scope) {
            console.log("scope", scope)
            return ElTableColumnDefaultSlot(scope)
          }
        }}
      >
      </MutliColumn>
    )
  })

  return (
    <el-table-column
      label={itemColumn.label}
      prop={itemColumn.prop}
      { ...(itemColumn.attrs || {}) }
      scopedSlots={{
        default(scope) {
          return ElTableColumnDefaultSlot(scope)
        }
      }}
    >
      { children }
    </el-table-column>
  )
}
